import Head from "next/head";
import { Inter } from "next/font/google";
import { useTheme } from "@/stores/theme";
const inter = Inter({ subsets: ["latin"] });

import { Main, Container } from "../styles/index/style";

import CurrentDate from "@/components/Date";
import ProgressBar from "@/components/ProgressBar";
import Filter from "@/components/Filter";
import AddTask from "@/components/AddTask";
import TasksContainer from "@/components/TasksContainer";

export default function Home() {
  const { theme } = useTheme();

  return (
    <>
      <Head>
        <title>Gerenciador de Tarefas - by Emerson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main theme={theme}>
        <Container theme={theme}>
          <CurrentDate />
          <ProgressBar />
          <Filter />
          <AddTask />
          <TasksContainer />
        </Container>
      </Main>
    </>
  );
}
